blank_issues_enabled: false
contact_links:
  - name: Add more templates issue
    url: https://github.com/tsparticles/404-templates/issues/97
    about: All other issues proposing new templates will be closed
  - name: Official tsParticles Repository
    url: https://github.com/matteobruni/tsparticles
    about: The official tsParticles GitHub Repository, where you can ask support about tsParticles library.
  - name: Official tsParticles Slack
    url: https://join.slack.com/t/tsparticles/shared_invite/enQtOTcxNTQxNjQ4NzkxLWE2MTZhZWExMWRmOWI5MTMxNjczOGE1Yjk0MjViYjdkYTUzODM3OTc5MGQ5MjFlODc4MzE0N2Q1OWQxZDc1YzI
    about: The official Slack offers more direct support.
  - name: Official tsParticles Discord
    url: https://discord.com/invite/hACwv45Hme
    about: The official Discord offers more direct support.
  - name: Official tsParticles Telegram
    url: https://t.me/tsparticles
    about: The official Telegram offers more direct support.
  - name: Official tsParticles Reddit
    url: https://www.reddit.com/r/tsParticles/
    about: The official Reddit offers more direct support.
